### ISSUE TITLE
7.2. Verifying an authentication assertion

### ISSUE THREAD

**Issue by rr-developer** [madwizard-org/webauthn-server#1]
Hi, I have been having a look at your project and it looks great.

I have also been trying to code the server side of webauthn and bumped into a problem with point '7.2. Verifying an authentication assertion' ( https://www.w3.org/TR/webauthn/#verifying-assertion ), and I think you might want to know about it.

Verification step 16 says: "Using the credential public key looked up in step 3, verify that sig is a valid signature **over the binary concatenation of aData and hash**." Doing just that I always got a signature that did not match with 'sig'. I spent a lot of hours checking my code without finding anything wrong. I inspected several source codes, including yours, and I found out that this repository, https://github.com/fido-alliance/webauthn-demo, did the verification differently. I tried it and it worked.
The correct concatenation that produces a valid signature is:
**rpIdHash + flags (1 byte) + signature counter (4 bytes) + clientDataHash**

I hope it helps. I suppose the W3C specification will be updated. By the way, I am using a 'FIDO2 Security Key' by Yubico.

Regards.

**Comment by madwizard-thomas** [comment]
Hi,
Thanks for the heads up, the assertion verifier is still a work in progress so I haven't tested the signature code yet. The attestation verifier uses a similar signature format though, it depends on the attestation format.  The latest work-in-progress version of the spec does have a [note](https://w3c.github.io/webauthn/#sctn-fido-u2f-sig-format-compat) about this in paragraph [7.2](https://w3c.github.io/webauthn/#verifying-assertion).
Kinds regards,
Thomas

**Comment by madwizard-thomas** [comment]
Actually I think the the original text is correct, because the authenticator data for an assertion consists of `rpIdHash ||  flag || signCount` (see [AuthenticatorData](https://github.com/madwizard-thomas/webauthn-server/blob/master/src/Attestation/AuthenticatorData.php)). So this data concatenated with clientDataHash is the correct signature data.

**Comment by rr-developer** [comment]
Yes, you are right. The origin of my problem seems to be that I was using this specification:
https://www.w3.org/TR/webauthn/ (20th March 2018)
instead of this one:
https://w3c.github.io/webauthn/ (6th July 2018)
